seed: 42
resume_from_checkpoint: null
allow_remote_model_source: false
model_name_or_path: ../models/Qwen3-8B
trust_remote_code: true
torch_dtype: bfloat16
attn_implementation: sdpa
enable_thinking: false
system_prompt_path: prompts/medical_relation_extraction_system_prompt.txt
train_path: data/processed/Comp6713-Ddi-Ade-Extraction_final_augment/merged_chatml_train.jsonl
validation_path: data/processed/Comp6713-Ddi-Ade-Extraction_final_augment/merged_chatml_validation.jsonl
max_seq_length: 4096
finetune_type: lora
load_in_4bit: false
bnb_4bit_quant_type: nf4
bnb_4bit_compute_dtype: bfloat16
bnb_4bit_use_double_quant: true
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
use_rslora: true
use_dora: false
init_lora_weights: true
target_modules: all-linear
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 0.000035
num_train_epochs: 4
warmup_ratio: 0.06
logging_steps: 20
save_strategy: steps
save_steps: 155
eval_strategy: steps
output_dir: outputs/qwen3_8b_lora_ddi_ade_final_aug_e4
per_device_eval_batch_size: 4
eval_steps: 155
save_total_limit: 3
gradient_checkpointing: true
remove_unused_columns: false
report_to: none
bf16: true
fp16: false
weight_decay: 0.02
lr_scheduler_type: cosine
max_grad_norm: 1.0
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
bias: none
task_type: CAUSAL_LM
modules_to_save: null
label_smoothing_factor: 0.03
train_sampling_strategy: weighted
empty_target_sampling_weight: 2.0
ddi_sampling_weight: 1.6
ddi_int_sampling_weight: 2.8
multi_relation_sampling_weight: 1.15
use_sample_loss_weights: true
empty_target_loss_weight: 1.2
ddi_loss_weight: 1.15
ddi_int_loss_weight: 2.0
multi_relation_loss_weight: 1.1
adapter_optimizer: default
loraplus_lr_ratio: 16.0
loraplus_lr_embedding: 0.000001
loraplus_weight_decay: null
